# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal Blog
email: blog@minimal.com
description: "O Minimal Blog é um blog minimalista feito em Jekyll para aprender as maravilhas que ele tem."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
shortname: "sidnei-simmon"
google_analytics: "UA-124574587-1"
# Build settings
markdown: kramdown
